name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

  static-checks:
    name: Static checks
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Run static checks
        run: npm run lint:ci

  tests:
    name: Unit tests
    needs: setup
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: food-diary-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        shell: bash -l {0}
        run: nvm install

      - name: Restore cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Migrate database
        run: npm run migrate:latest
        env:
          NODE_ENV: test

      - name: Run unit tests and check coverage
        run: npm test